放送コンポーネントの作成
80PercentBloom/enzivia-no-izumi pull request #33
Opened 2021-10-31 03:50 UTC by 97liar

### やったこと
 
・放送、放送一覧コンポーネントを作成しました
・TypescriptでESLintが絶対パスに関する警告を出さないようにしました
・放送ステータス用コンポーネントの微修正しました

### チケットへのリンク
 
https://github.com/80PercentBloom/enzivia-no-izumi/issues/8

### 動作確認

放送コンポーネントを１つで一覧を表示
放送コンポーネントを２つで一覧を表示
放送コンポーネントを３つで一覧を表示
⇛想定通りの結果（画像添付します）

### 確認事項
- [x] `yarn dev` で問題なく動くか?
- [x] `yarn build` が失敗しないか?
- [x] コード中にeslint, prettierのエラー・警告がないか？

### 悩み・相談事項

・yarn build時にeslintがエラーが出していたので設定ファイルを変更して解消しました。
解消方法に問題がない確認していただきたいです。対象ファイル「.eslintrc.js」

・放送コンポーネントと放送一覧コンポーネントを分けて作りました。
（放送一覧コンポーネントはN個の放送コンポーネントに対してCSSを当てているだけです）
プルリクする時に思ったのですがどこまで作成すればよいか明確にできていなかったなと思いましたので、
不要であったり考え方など間違っている箇所があればご指摘お願いいたします！

### スクリーンショットや動画など 📸 🎥

![スクリーンショット 2021-10-31 1 02 38](https://user-images.githubusercontent.com/88515920/139566593-e7b770b0-2782-4485-99e8-d8f39a72aeaa.png)
![スクリーンショット 2021-10-31 1 02 19](https://user-images.githubusercontent.com/88515920/139566600-d8e477a0-87b6-434e-b263-1d593da8a660.png)
![スクリーンショット 2021-10-31 1 01 40](https://user-images.githubusercontent.com/88515920/139566603-6efdba59-07fe-4434-9fd2-db23f5370c8f.png)

2021-10-31 05:09 UTC, kyoichi1 requested changes
お疲れ様です！一箇所だけ気づいたところあったのでレビューさせて頂きました！

2021-10-31 05:09 UTC, kyoichi1 commented on src/components/Broadcast/index.tsx
> +    status: 'beofre-broadcast',
お疲れ様です
beofre となっておりますが、beforeではないでしょうか^ ^？

2021-10-31 12:22 UTC, shuheeeei reviewed
コンポーネント構造の見直しをお願いします :pray:

2021-10-31 12:22 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +const BROADCAST_INFO = [
[IMO]
これらの値は `Broadcast` コンポーネントが props として与えられるものだと思います

2021-10-31 12:22 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +          {/* API方針決まり次第変更 */}
URLの方針、ですかね？

2021-10-31 12:22 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +        <ul className="broadcast-list-component-base mt-4 ">
`Broadcast` という単数を表すコンポーネントであることはOKです 👍 
が、その中身が ul を使用したリスト構造になっているのはおかしいですね
ul の子要素の li の中身が この `Broadcast` コンポーネントになると思います

2021-10-31 12:22 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +          <Link href={`/broadcasts/${broadcastId}`}>
ul 要素の子要素(直下)に li 以外が来るのは、HTMLの構造的にNGです 🙅‍♂️ 
構成を見直していただきたく... 🙏

2021-10-31 12:22 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +        <ul className="broadcast-list-component-base mt-2 mb-4">
放送コンポーネント下部がulで表現されているのはなぜでしょうか？ 🤔 
リスト的な要素はないのかなぁとおもいます

2021-10-31 12:24 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +            <BroadcastStatus status="on-air" />
追加です:pray:

こちらの status にはitemの status を渡すべきかと思います〜
そうすれば BROADCAST_INFO のタイポにも気づけたのかなと思われます

2021-11-01 12:47 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +          {/* API方針決まり次第変更 */}
URLの「:broadcastId」になる部分がAPIから渡ってくるものだと想定しており、そこの渡され方が決まり次第変更が必要かと思っていましたが、いったんpropsで充てるようにすれば良い感じでしょうか！
イメージ：<Link href={`/broadcasts/${props.id}>

2021-11-01 15:37 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +const BROADCAST_INFO = [
`Broadcasts`コンポーネントにて配列mapを行い、スプレッドで引数を渡すように修正しました！

2021-11-01 15:39 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +          {/* API方針決まり次第変更 */}
勘違いしておりました！:broadcastidは放送コンポーネントのデータと別に来るものだと考えて渡され方が異なると思っていましたが、一旦放送コンポーネントのデータに含まれている想定で持ってくるようにしました！

2021-11-01 15:43 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +        <ul className="broadcast-list-component-base mt-4 ">
`Broadcast`コンポーネントの作り方を少し見直してみました。

2021-11-01 15:44 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +          <Link href={`/broadcasts/${broadcastId}`}>
全体的に構造を見直しました。まだおかしいな場所がありましたらご指摘のほどお願いいたします。。。🙇‍♂️

2021-11-01 15:46 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +        <ul className="broadcast-list-component-base mt-2 mb-4">
リストに対する認識がずれておりました。。修正しましたのでご確認お願いいたします。

2021-11-01 15:47 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +            <BroadcastStatus status="on-air" />
ほんとですね。。。
ありがとうございます🙇‍♂️
引数を渡すように修正しました！

2021-11-02 05:36 UTC, kyoichi1 approved these changes

2021-11-03 14:23 UTC, shuheeeei reviewed
ごめんなさい！気が付かずいまコメントしました:bow: :bow:

2021-11-03 14:23 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +}: BroadcastInfo) => (
この `BroadcastInfo` はこのファイル内で定義したいですねぇ...

2021-11-03 14:23 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +  ymd,
`ymd` という命名はあまりよろしくないですね 🤔 
なんの日？という情報がないからです。
作成日でしたらよく `createAt` が使われます

2021-11-03 14:23 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +        <p className="broadcast-list-text-base ml-2">{ymd}</p>
ここは文章ではないので、 p タグよりも span タグのほうが適切そうです

2021-11-03 14:23 UTC, shuheeeei commented on src/components/Broadcasts/index.tsx
> +import { Props } from '../BroadcastStatus';
import するのはいったんこのままでいいですが、以下の修正をお願いします 🙏 
- 以下のようにしてみてください ( `type import` と言います )
```suggestion
import  type { Props } from '../BroadcastStatus';
```
- 命名が Props のままだとなんの型定義なのかわからないので、名前を変えましょう!
  - `as` を使って別名称で import できます
```suggestion
import type { Props as Hoge } from '../BroadcastStatus';
```

2021-11-03 14:23 UTC, shuheeeei commented on src/components/Broadcasts/index.tsx
> +export type BroadcastInfo = {
ここの型定義を `src/components/Broadcast/index.tsx` に書いてください的なことを書きましたが、じゃあどうすんねん、ということで対応を書きます〜

まず `import type { ComponentProps } from 'react';` で `ComponentProps` という型をもってきます。
そして、 以下のようにすれば `Broadcast` コンポーネントのpropsの型を持ってこれます。
```js
type BroadcastInfo = ComponentProps<typeof Broadcast>;
```

これでいけるはずです！

2021-11-06 07:04 UTC, 97liar commented
放送ステータス用のコンポーネントを`BroadcastStatus`
放送ステータスの型を`broadcastStatuts`
とほとんど一緒になってしまっているのがあまりよくないかなと思いながらもプルリクいたしました。。。
他に適切な名前がございましたら教えてください！（命名難しい。。。）

2021-11-06 07:06 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +        <p className="broadcast-list-text-base ml-2">{ymd}</p>
pタグ；文章
spanタグ；文字のかたまり、１単語
といった感じでしょうか？

2021-11-06 07:07 UTC, 97liar commented on src/components/Broadcast/index.tsx
> +  ymd,
放送日なので`broadcastAt`にしてみましたがいかがでしょうか。。？

2021-11-06 09:34 UTC, shuheeeei approved these changes
いったんOKです！
以下だけご対応くださいな〜
👇

> 放送ステータス用のコンポーネントをBroadcastStatus
> 放送ステータスの型をbroadcastStatuts
> とほとんど一緒になってしまっているのがあまりよくないかなと思いながらもプルリクいたしました。。。
> 他に適切な名前がございましたら教えてください！（命名難しい。。。）

コンポーネント名とそのpropの型の名称がかぶるのはよくあることなんですが、型の名前はパスカルケースにしたいですね~
慣例としてよくあるのは、コンポーネント名が`Hoge`ならそのpropsの型名は`HogeProps`にする、という感じですね
ということで型名を直してみてください！

2021-11-06 09:56 UTC, shuheeeei commented on src/components/Broadcast/index.tsx
> +        <p className="broadcast-list-text-base ml-2">{ymd}</p>
おおっと、スルーしてました 🙏 
おっしゃるとおりです！

2021-11-06 10:07 UTC, 97liar commented
@shuheeeei さん
何度もレビューしていただきありがとうございます。
また型名についてご説明ありがとうございます！！
コンポーネント名と引数の型名の関係について覚えておきます！

2021-11-07 11:37 UTC, merged